import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import { config } from 'dotenv';
config({ path: '.env' });
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });
const key = await prisma.serviceApiKey.findFirst({ where: { service: 'RECOMMENDATION' } });
console.log("Current apiKey value:", key?.apiKey);
await prisma.$disconnect();
